"""
Generated EXPECTED_SCHEMAS dictionary from SSOT baseline.
Updated on July 2026 to include all 17 active tables (migrations through 058).
This provides compatibility with verify_database.py and other validation scripts.
"""

from typing import Dict, Any, List

# Expected schema definitions for validation scripts
EXPECTED_SCHEMAS: Dict[str, Dict[str, Any]] = {
    "account_balances": {
        "required_fields": {
            "account_id": "text",
            "buying_power": "numeric",
            "cash": "numeric",
            "currency_code": "text",
            "currency_id": "text",
            "currency_name": "text",
            "snapshot_date": "date",
            "sync_timestamp": "timestamptz",
        },
        "primary_keys": ["currency_code", "snapshot_date", "account_id"],
        "description": "Auto-generated from account_balances table",
    },
    "accounts": {
        "required_fields": {
            "brokerage_authorization": "text",
            "id": "text",
            "institution_name": "text",
            "last_successful_sync": "timestamptz",
            "name": "text",
            "number": "text",
            "portfolio_group": "text",
            "sync_timestamp": "timestamptz",
            "total_equity": "numeric",
        },
        "primary_keys": ["id"],
        "description": "Auto-generated from accounts table",
    },
    "discord_market_clean": {
        "required_fields": {
            "author": "text",
            "cleaned_content": "text",
            "content": "text",
            "message_id": "text",
            "processed_at": "timestamp",
            "sentiment": "numeric",
            "timestamp": "text",
        },
        "primary_keys": ["message_id"],
        "description": "Auto-generated from discord_market_clean table",
    },
    "discord_messages": {
        "required_fields": {
            "attachments": "text",
            "author": "text",
            "author_id": "bigint",
            "channel": "text",
            "channel_type": "text",
            "content": "text",
            "created_at": "timestamp",
            "error_reason": "text",
            "is_bot": "boolean",
            "is_command": "boolean",
            "is_reply": "boolean",
            "mentions": "text",
            "message_id": "text",
            "num_chars": "integer",
            "num_words": "integer",
            "parse_status": "text",
            "prompt_version": "text",
            "reply_to_id": "bigint",
            "sentiment_score": "numeric",
            "tickers_detected": "text",
            "timestamp": "text",
            "tweet_urls": "text",
            "user_id": "text",
        },
        "primary_keys": ["message_id"],
        "description": "Auto-generated from discord_messages table",
    },
    "discord_parsed_ideas": {
        "required_fields": {
            "action": "text",
            "author_id": "text",
            "channel_id": "text",
            "confidence": "numeric",
            "context_summary": "text",
            "direction": "text",
            "expiry": "date",
            "id": "text",
            "idea_index": "integer",
            "idea_summary": "text",
            "idea_text": "text",
            "instrument": "text",
            "is_noise": "boolean",
            "label_scores": "json",
            "labels": "array",
            "levels": "json",
            "local_idea_index": "integer",
            "message_id": "text",
            "model": "text",
            "option_type": "text",
            "parsed_at": "timestamptz",
            "premium": "numeric",
            "primary_symbol": "text",
            "prompt_version": "text",
            "raw_json": "json",
            "soft_chunk_index": "integer",
            "source_created_at": "timestamptz",
            "strike": "numeric",
            "symbols": "array",
            "time_horizon": "text",
            "trigger_condition": "text",
        },
        "primary_keys": ["id"],
        "description": "Auto-generated from discord_parsed_ideas table",
    },
    "discord_trading_clean": {
        "required_fields": {
            "author": "text",
            "cleaned_content": "text",
            "content": "text",
            "message_id": "text",
            "processed_at": "timestamp",
            "sentiment": "numeric",
            "stock_mentions": "text",
            "timestamp": "text",
        },
        "primary_keys": ["message_id"],
        "description": "Auto-generated from discord_trading_clean table",
    },
    "institutional_holdings": {
        "required_fields": {
            "company_name": "text",
            "created_at": "timestamptz",
            "cusip": "text",
            "filing_date": "date",
            "id": "integer",
            "is_call": "boolean",
            "is_put": "boolean",
            "manager_cik": "text",
            "manager_name": "text",
            "share_type": "text",
            "shares": "bigint",
            "ticker": "text",
            "value_usd": "bigint",
        },
        "primary_keys": ["id"],
        "description": "Auto-generated from institutional_holdings table",
    },
    "ohlcv_daily": {
        "required_fields": {
            "symbol": "text",
            "date": "date",
            "open": "numeric",
            "high": "numeric",
            "low": "numeric",
            "close": "numeric",
            "volume": "bigint",
            "source": "text",
            "created_at": "timestamptz",
            "updated_at": "timestamptz",
        },
        "primary_keys": ["symbol", "date"],
        "description": "Databento OHLCV daily bars",
    },
    "orders": {
        "required_fields": {
            "account_id": "text",
            "action": "text",
            "brokerage_order_id": "text",
            "canceled_quantity": "numeric",
            "child_brokerage_order_ids": "json",
            "created_at": "timestamp",
            "execution_price": "numeric",
            "expiry_date": "date",
            "filled_quantity": "numeric",
            "limit_price": "numeric",
            "notified": "boolean",
            "open_quantity": "numeric",
            "option_expiry": "date",
            "option_right": "text",
            "option_strike": "numeric",
            "option_ticker": "text",
            "order_type": "text",
            "status": "text",
            "stop_price": "numeric",
            "symbol": "text",
            "sync_timestamp": "timestamptz",
            "time_executed": "timestamp",
            "time_in_force": "text",
            "time_placed": "timestamp",
            "time_updated": "timestamp",
            "total_quantity": "numeric",
            "updated_at": "timestamp",
            "user_id": "text",
        },
        "primary_keys": ["brokerage_order_id"],
        "description": "Auto-generated from orders table",
    },
    "positions": {
        "required_fields": {
            "account_id": "text",
            "asset_type": "text",
            "average_buy_price": "numeric",
            "created_at": "timestamp",
            "currency": "text",
            "equity": "numeric",
            "exchange_code": "text",
            "exchange_name": "text",
            "figi_code": "text",
            "logo_url": "text",
            "mic_code": "text",
            "open_pnl": "numeric",
            "price": "numeric",
            "quantity": "numeric",
            "raw_symbol": "text",
            "symbol": "text",
            "symbol_description": "text",
            "symbol_id": "text",
            "sync_timestamp": "timestamptz",
            "current_price": "numeric",
            "prev_price": "numeric",
            "price_updated_at": "timestamptz",
        },
        "primary_keys": ["symbol", "account_id"],
        "description": "Auto-generated from positions table",
    },
    "processing_status": {
        "required_fields": {
            "channel": "text",
            "message_id": "text",
            "processed_for_cleaning": "boolean",
            "processed_for_twitter": "boolean",
            "updated_at": "timestamp",
        },
        "primary_keys": ["message_id", "channel"],
        "description": "Auto-generated from processing_status table",
    },
    "schema_migrations": {
        "required_fields": {
            "applied_at": "timestamp",
            "description": "text",
            "version": "text",
        },
        "primary_keys": ["version"],
        "description": "Auto-generated from schema_migrations table",
    },
    "symbol_aliases": {
        "required_fields": {
            "alias": "text",
            "created_at": "timestamptz",
            "id": "integer",
            "source": "text",
            "ticker": "text",
            "updated_at": "timestamptz",
        },
        "primary_keys": ["id"],
        "description": "Auto-generated from symbol_aliases table",
    },
    "symbols": {
        "required_fields": {
            "asset_type": "text",
            "base_currency_code": "text",
            "created_at": "timestamp",
            "description": "text",
            "exchange_code": "text",
            "exchange_mic": "text",
            "exchange_name": "text",
            "figi_code": "text",
            "id": "text",
            "is_quotable": "boolean",
            "is_supported": "boolean",
            "is_tradable": "boolean",
            "logo_url": "text",
            "market_close_time": "time",
            "market_open_time": "time",
            "raw_symbol": "text",
            "ticker": "text",
            "timezone": "text",
            "type_code": "text",
            "updated_at": "timestamp",
        },
        "primary_keys": ["id"],
        "description": "Auto-generated from symbols table",
    },
    "stock_profile_current": {
        "required_fields": {
            "ticker": "text",
            "last_updated": "timestamptz",
            "latest_close_price": "numeric",
            "previous_close_price": "numeric",
            "daily_change_pct": "numeric",
            "return_1w_pct": "numeric",
            "return_1m_pct": "numeric",
            "return_3m_pct": "numeric",
            "return_1y_pct": "numeric",
            "volatility_30d": "numeric",
            "volatility_90d": "numeric",
            "year_high": "numeric",
            "year_low": "numeric",
            "avg_volume_30d": "bigint",
            "current_position_qty": "numeric",
            "current_position_value": "numeric",
            "avg_buy_price": "numeric",
            "unrealized_pnl": "numeric",
            "unrealized_pnl_pct": "numeric",
            "total_orders_count": "integer",
            "buy_orders_count": "integer",
            "sell_orders_count": "integer",
            "avg_order_size": "numeric",
            "first_trade_date": "date",
            "last_trade_date": "date",
            "total_mention_count": "integer",
            "mention_count_30d": "integer",
            "mention_count_7d": "integer",
            "avg_sentiment_score": "numeric",
            "bullish_mention_pct": "numeric",
            "bearish_mention_pct": "numeric",
            "neutral_mention_pct": "numeric",
            "first_mentioned_at": "timestamptz",
            "last_mentioned_at": "timestamptz",
            "label_trade_execution_count": "integer",
            "label_trade_plan_count": "integer",
            "label_technical_analysis_count": "integer",
            "label_options_count": "integer",
            "label_catalyst_news_count": "integer",
            "created_at": "timestamptz",
            "updated_at": "timestamptz",
        },
        "primary_keys": ["ticker"],
        "description": "One row per ticker with latest derived metrics (migration 055)",
    },
    "stock_profile_history": {
        "required_fields": {
            "ticker": "text",
            "as_of_date": "date",
            "close_price": "numeric",
            "daily_change_pct": "numeric",
            "return_1w_pct": "numeric",
            "return_1m_pct": "numeric",
            "return_3m_pct": "numeric",
            "return_1y_pct": "numeric",
            "volatility_30d": "numeric",
            "volatility_90d": "numeric",
            "year_high": "numeric",
            "year_low": "numeric",
            "avg_volume_30d": "bigint",
            "position_qty": "numeric",
            "position_value": "numeric",
            "avg_buy_price": "numeric",
            "unrealized_pnl": "numeric",
            "unrealized_pnl_pct": "numeric",
            "total_orders_count": "integer",
            "total_mention_count": "integer",
            "mention_count_30d": "integer",
            "avg_sentiment_score": "numeric",
            "bullish_mention_pct": "numeric",
            "created_at": "timestamptz",
        },
        "primary_keys": ["ticker", "as_of_date"],
        "description": "Time-series of profile metrics per ticker (migration 055)",
    },
    "twitter_data": {
        "required_fields": {
            "author": "text",
            "author_name": "text",
            "author_username": "text",
            "channel": "text",
            "content": "text",
            "created_at": "timestamp",
            "discord_date": "timestamptz",
            "discord_message_id": "text",
            "discord_sent_date": "timestamptz",
            "like_count": "integer",
            "media_urls": "json",
            "message_id": "text",
            "quote_count": "integer",
            "reply_count": "integer",
            "retrieved_at": "text",
            "retweet_count": "integer",
            "source_url": "text",
            "stock_tags": "text",
            "tweet_content": "text",
            "tweet_created_date": "timestamptz",
            "tweet_date": "timestamptz",
            "tweet_id": "text",
        },
        "primary_keys": ["tweet_id"],
        "description": "Auto-generated from twitter_data table",
    },
}

# Schema metadata for reference
SCHEMA_METADATA = {
    "generated_at": "2026-07-11",
    "source_files": [
        "000_baseline.sql",
        "015_primary_key_alignment.sql",
        "016_complete_rls_policies.sql",
        "017_timestamp_field_migration.sql",
        "018_cleanup_schema_drift.sql",
        "019_data_quality_cleanup.sql",
        "020_drop_positions_redundant_columns.sql",
        "021_fix_processing_status_composite_key.sql",
        "022_add_attachments_column.sql",
        "023_event_contract_tables.sql",
        "024_account_balances_unique_constraint.sql",
        "025_drop_backup_tables.sql",
        "026_add_twitter_media_column.sql",
        "027_institutional_holdings.sql",
        "028_add_raw_symbol_to_positions.sql",
        "029_fix_account_balances_pk.sql",
        "030_discord_message_chunks.sql",
        "031_stock_mentions.sql",
        "032_add_chunk_metadata.sql",
        "033_stock_mentions_v2.sql",
        "034_add_primary_symbol_column.sql",
        "035_chunk_segmentation_fields.sql",
        "036_llm_tagging_columns.sql",
        "037_gold_label_columns.sql",
        "038_discord_idea_units.sql",
        "039_add_parse_status_to_discord_messages.sql",
        "040_create_discord_parsed_ideas.sql",
        "041_fix_parsed_ideas_message_id_type.sql",
        "042_add_chunk_indexing_columns.sql",
        "043_add_parsed_ideas_foreign_key.sql",
        "044_drop_duplicate_indexes.sql",
        "045_consolidate_rls_policies.sql",
        "046_drop_remaining_duplicate_indexes.sql",
        "047_document_trade_history.sql",
        "048_drop_unused_nlp_indexes.sql",
        "049_drop_legacy_tables.sql",
        "051_drop_legacy_price_tables.sql",
        "052_drop_orphaned_tables.sql",
        "053_symbol_aliases.sql",
        "054_drop_chart_metadata.sql",
        "055_stock_profiles.sql",
        "056_add_message_flags.sql",
        "057_add_orders_notified.sql",
        "058_security_and_indexes.sql",
    ],
    "table_count": 17,
    "total_columns": 260,
}
